[build.environment]
  NODE_VERSION = "20.19.0"
  NPM_VERSION = "10.0.0"

[build]
  command = "node -v && npm -v && npm install && npm run build"
  publish = "dist"
  functions = "netlify/functions"

[dev]
  framework = "#custom"
  command = "npm run dev"
  targetPort = 3001
  port = 3001

[[redirects]]
  from = "https://yavuli.netlify.app/*"
  to = "https://yavuli.app/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
